[package]
authors = []
name = "navori"
version = "1.0.0"

[addresses]
lib_addr = "_"
verifier_addr = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.17"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
libs = { local = "../libs" }

[dev-dependencies]
